django_project/urls.py
from django.contrib import admin
from django.urls import path
from users.views import home_view, register_view, login_view
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home_view, name='home'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('', TemplateView.as_view(template_name='index.html'), name='react'),
]

django_tvqa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include('users.urls')),
    path('', include('pmods.urls')),
]

pmods/urls.py
from .views import pmod_bom_create_view, pmod_bom_list_view, pmod_bom_update_view
from django.urls import path

app_name = 'pmods'

urlpatterns = [
    path('pmod_bom_create/', pmod_bom_create_view, name='pmod_bom_create'),
    path('pmod_bom_list/', pmod_bom_list_view, name='pmod_bom_list'),
    path('pmod_bom_list/<id>/update', pmod_bom_update_view, name='pmod_bom_update'),
]

posts/urls.py
from .views import post_view, SearchResultsView
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('', post_view, name='index'),
    path('home/', post_view, name='home'),
]

users/urls.py
from django.urls import path
from .views import register_view
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% comment "TODO: scss" %}
    <link href="{% sass_src '/css/_footer.scss' %}" rel="stylesheet" type="text/css" />
    {% endcomment %}
    <title>Welcome To TVQA</title>
  </head>
  <body>
    {% block content %}
        Hello Stranger!
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/carousel.html
<div class="container">
  <div id="carouselExampleControls" class="carousel slide bg-light" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="../static/images/sony_tv1.jpg" class="d-block w-60" alt="...">
      </div>
      <div class="carousel-item">
        <img src="../static/images/sony_tv2.jpg" class="d-block w-60" alt="...">
      </div>
      <div class="carousel-item">
        <img src="../static/images/sony_tv3.jpg" class="d-block w-60" alt="...">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

templates/footer.html
<div class="container">
  <footer class="bd-footer p-3 p-md-5 mt-5 text-center text-muted bg-light">
      <div class="container">
        <ul class="list-inline mx-auto justify-content-center">
          <li class="list-inline-item"><a href="#">Contact</a></li>
          <li class="list-inline-item"><a href="#">Links</a></li>
          <li class="list-inline-item"><a href="#">Examples</a></li>
          <li class="list-inline-item"><a href="#">About</a></li>
        </ul>
        <p class="mb-0">Designed and built with all the love in the world by the <a href="#">TVQA Team</a> with the help of <a href="#">our contributors</a>.</p>
        <p class="mb-0">Currently v0.0.1. The TVQA-System is <a href="#">open source</a> under the MIT license.</p>
      </div>
  </footer>
</div>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% include 'navbar.html' %}
    {% include 'jumbotron.html' %}
    {% include 'carousel.html' %}
    <div class="container" id="articles-post">
        <div class="posts-container mx-auto px-3 my-5">
            <div class="posts">
                <div class="post">
                    <h1 class="post-title fw-500">
                        Hello, world!
                    </h1>
                    <p>
                        Est nisi cupidatat magna sunt aliqua. Magna velit cupidatat minim cupidatat proident eiusmod deserunt. Ad pariatur veniam velit occaecat eiusmod. Anim adipisicing anim quis nisi esse veniam sit officia cupidatat qui occaecat. Minim elit cupidatat duis culpa consequat commodo deserunt pariatur. Irure aliqua laborum non aliqua amet enim.
                    </p>
                    <hr class="my-4">
                    <p>
                        <strong>Jump to a section:</strong>
                    </p>
                    <ul>
                        {% for post in posts %}
                        <li><a href="#post{{ post.id }}">{{ post.title }}</a></li>
                        {% endfor %}
                    </ul>
                    <hr class="my-4">
                    {% for post in posts %}
                    <h2 id="post{{ post.id }}">{{ post.title }}</h2>
                    <p class="text-muted">  
                        <small>{{ post.author }}, {{ post.date_posted|date:"Y F d"}}</small>
                    </p>
                    <p>
                        {{ post.content }}
                    </p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% include 'footer.html' %}
</div>
{% endblock %}

templates/index1.html
{% extends 'base.html' %}

{% block replaceme %}
<div class="m-3">
    <div class="posts-container mx-auto px-3 my-5">
        <div class="posts">
            <div class="post">
                <h1 class="post-title fw-500">
                    Hello, world!
                </h1>
                <p>
                    Est nisi cupidatat magna sunt aliqua. Magna velit cupidatat minim cupidatat proident eiusmod deserunt. Ad pariatur veniam velit occaecat eiusmod. Anim adipisicing anim quis nisi esse veniam sit officia cupidatat qui occaecat. Minim elit cupidatat duis culpa consequat commodo deserunt pariatur. Irure aliqua laborum non aliqua amet enim.
                </p>
                <hr class="my-4">
                <p>
                    <strong>Jump to a section:</strong>
                </p>
                <ul>
                    <li><a href="#css-grid">CSS Grid</a></li>
                    <li><a href="#offcanvas-in-navbars">Offcanvas in navbars</a></li>
                    <li><a href="#placeholders">Placeholders</a></li>
                    <li><a href="#horizontal-collapse">Horizontal collapse</a></li>
                    <li><a href="#stack-and-vertical-rule-helper">Stack and vertical rule helpers</a></li>
                    <li><a href="#new-css-variables">New CSS variables</a></li>
                    <li><a href="#updated">Updated <code class="language-plaintext highlighter-rouge">.bg-*</code> and <code class="language-plaintext highlighter-rouge">.text-*</code> utilities</a></li>
                    <li><a href="#four-new-examples">Four new examples</a></li>
                    <li><a href="#modal-and-offcanvas-backdrops">Modal and offcanvas backdrops</a></li>
                </ul>
                <hr class="my-4">
                <h2 id="css-grid">CSS Grid</h2>
                <p>
                    Qui sunt ea ea cillum ex magna eiusmod. Sit est nulla cupidatat adipisicing. Ad cillum deserunt cillum reprehenderit enim sit ipsum ut excepteur. Cupidatat esse et fugiat mollit est qui mollit tempor nisi velit Lorem est ut. Mollit irure ex mollit occaecat laborum et officia laboris anim.
                </p>
                <p>
                    Esse culpa exercitation velit sunt. Cillum eiusmod tempor ullamco id cillum ex aliquip incididunt quis. Amet veniam quis laborum adipisicing. Minim Lorem cupidatat exercitation exercitation deserunt. Et aliqua cillum duis velit sit adipisicing anim.
                <p>
                    Enim labore do velit est ut ut consectetur tempor aliqua. Enim deserunt elit dolor duis ut minim ad ex. In tempor dolore aliqua cupidatat proident nulla tempor ad anim.
                </p>
                <h2 id="offcanvas-in-navbars">Offcanvas in navbars</h2>
                <p>
                    Qui sunt ea ea cillum ex magna eiusmod. Sit est nulla cupidatat adipisicing. Ad cillum deserunt cillum reprehenderit enim sit ipsum ut excepteur. Cupidatat esse et fugiat mollit est qui mollit tempor nisi velit Lorem est ut. Mollit irure ex mollit occaecat laborum et officia laboris anim.
                </p>
                <p>
                    Est velit non eu cillum consequat pariatur dolore commodo. Dolor mollit eiusmod qui exercitation consectetur reprehenderit in voluptate. Incididunt labore labore reprehenderit sint. Sit enim quis voluptate pariatur esse. Sint proident et veniam aliqua.
                </p>
                <p>
                    Commodo officia ea nisi nisi sit. Pariatur eu Lorem nulla velit cillum. Fugiat enim cupidatat consectetur magna incididunt velit enim dolor. Sint fugiat reprehenderit quis ea occaecat est deserunt. Ipsum reprehenderit mollit minim et. Mollit nulla eu culpa exercitation veniam proident id consectetur proident non ut amet veniam.
                </p>
                <h2 id="placeholders">Placeholders</h2>
                <p>
                    Qui sunt ea ea cillum ex magna eiusmod. Sit est nulla cupidatat adipisicing. Ad cillum deserunt cillum reprehenderit enim sit ipsum ut excepteur. Cupidatat esse et fugiat mollit est qui mollit tempor nisi velit Lorem est ut. Mollit irure ex mollit occaecat laborum et officia laboris anim.
                </p>
                <p> 
                    Qui Lorem nulla voluptate ut cillum. Qui in nostrud consequat minim dolor. Veniam nisi velit quis qui non sunt labore in eiusmod aute magna dolor dolore magna. Dolor sint duis anim sint enim culpa. Aliquip culpa aliquip et laborum commodo nostrud anim ullamco duis. Ipsum nostrud fugiat laborum proident minim nisi.
                </p>
                <p> 
                    Aliqua reprehenderit veniam laboris nostrud occaecat excepteur consequat id ipsum laborum et nostrud aliquip tempor. Ex minim commodo velit dolore officia ullamco ipsum irure deserunt elit eiusmod irure. Ea cupidatat aliquip voluptate adipisicing laborum quis. Fugiat nisi deserunt reprehenderit eiusmod ex nulla. Ullamco ullamco irure est cupidatat id.
                </p>
                <h2 id="horizontal-collapse">Horizontal collapse</h2>
                <p>
                    Qui sunt ea ea cillum ex magna eiusmod. Sit est nulla cupidatat adipisicing. Ad cillum deserunt cillum reprehenderit enim sit ipsum ut excepteur. Cupidatat esse et fugiat mollit est qui mollit tempor nisi velit Lorem est ut. Mollit irure ex mollit occaecat laborum et officia laboris anim.
                </p>
                <p> 
                    Irure sit dolore commodo non non velit fugiat laboris officia cupidatat. Nisi sunt duis incididunt reprehenderit minim quis. Dolore ut nostrud mollit deserunt nisi irure eu do eu id non laborum.
                </p>
                <p> 
                    Ut laborum voluptate sint minim. Aute deserunt cupidatat do excepteur culpa adipisicing id aliqua veniam tempor sunt nostrud commodo. Laborum irure est ullamco aliqua mollit cillum commodo sit sint qui. Culpa culpa incididunt Lorem velit velit reprehenderit ex ipsum do. Reprehenderit eu eu sint consectetur sit duis labore est veniam in laborum qui incididunt sit.
                </p>
                <h2 id="stack-and-vertical-rule-helper">Stack and vertical rule helper</h2>
                <p>
                    Qui sunt ea ea cillum ex magna eiusmod. Sit est nulla cupidatat adipisicing. Ad cillum deserunt cillum reprehenderit enim sit ipsum ut excepteur. Cupidatat esse et fugiat mollit est qui mollit tempor nisi velit Lorem est ut. Mollit irure ex mollit occaecat laborum et officia laboris anim.
                </p>
                <h2 id="new-css-variables">New CSS variables</h2>
                <p>
                    Qui sunt ea ea cillum ex magna eiusmod. Sit est nulla cupidatat adipisicing. Ad cillum deserunt cillum reprehenderit enim sit ipsum ut excepteur. Cupidatat esse et fugiat mollit est qui mollit tempor nisi velit Lorem est ut. Mollit irure ex mollit occaecat laborum et officia laboris anim.
                </p>
                <h2 id="updated">Updated</h2>
                <p>
                    Qui sunt ea ea cillum ex magna eiusmod. Sit est nulla cupidatat adipisicing. Ad cillum deserunt cillum reprehenderit enim sit ipsum ut excepteur. Cupidatat esse et fugiat mollit est qui mollit tempor nisi velit Lorem est ut. Mollit irure ex mollit occaecat laborum et officia laboris anim.
                </p>
                <h2 id="four-new-examples">Four new examples</h2>
                <p>
                    Qui sunt ea ea cillum ex magna eiusmod. Sit est nulla cupidatat adipisicing. Ad cillum deserunt cillum reprehenderit enim sit ipsum ut excepteur. Cupidatat esse et fugiat mollit est qui mollit tempor nisi velit Lorem est ut. Mollit irure ex mollit occaecat laborum et officia laboris anim.
                </p>
                <h2 id="modal-and-offcanvas-backdrops">Modal and offcanvas backdrops</h2>
                <p>
                    Qui sunt ea ea cillum ex magna eiusmod. Sit est nulla cupidatat adipisicing. Ad cillum deserunt cillum reprehenderit enim sit ipsum ut excepteur. Cupidatat esse et fugiat mollit est qui mollit tempor nisi velit Lorem est ut. Mollit irure ex mollit occaecat laborum et officia laboris anim.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/jumbotron.html
<div class="container">
    <div class="jumbotron">
        {% if user.is_authenticated %}
        <h1 class="display-4">Hello, {{ user.username }}!</h1>
        {% else %}
        <h1 class="display-4">Hello, visitor!</h1>
        {% endif %}
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <p>
            Designed and developed by Zhang Liang.
        </p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="#articles-post" role="button">Read more</a>
    </div>
</div>

templates/navbar.html
<div class="container mb-sm-3">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="navbar-brand">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-tv" viewBox="0 0 16 16">
    <path d="M2.5 13.5A.5.5 0 0 1 3 13h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zM13.991 3l.024.001a1.46 1.46 0 0 1 .538.143.757.757 0 0 1 .302.254c.067.1.145.277.145.602v5.991l-.001.024a1.464 1.464 0 0 1-.143.538.758.758 0 0 1-.254.302c-.1.067-.277.145-.602.145H2.009l-.024-.001a1.464 1.464 0 0 1-.538-.143.758.758 0 0 1-.302-.254C1.078 10.502 1 10.325 1 10V4.009l.001-.024a1.46 1.46 0 0 1 .143-.538.758.758 0 0 1 .254-.302C1.498 3.078 1.675 3 2 3h11.991zM14 2H2C0 2 0 4 0 4v6c0 2 2 2 2 2h12c2 0 2-2 2-2V4c0-2-2-2-2-2z"></path>
    </svg>
    SSVE TVQA
  </div>  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        {% if user.is_authenticated %}
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Service
        </a>
        {% else %}
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown disabled" aria-haspopup="true" aria-expanded="false">
          Service
        </a>   
        {% endif %}
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'pmods:pmod_bom_create' %}">PMod RMA Buyback BOM Tracker</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'pmods:pmod_bom_list' %}">PMod RMA Query</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">WW PMod SMLD</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">WW TV SMLD</a>
        </div>
      </li>

      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}" tabindex="-1" aria-disabled="true">Log out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:register' %}" tabindex="-1" aria-disabled="true">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:login' %}" tabindex="-1" aria-disabled="true">Log in</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'posts:search_results' %}"  method="GET">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</div>